import type { Metadata } from "next";

import "./globals.css";
import ProviderWrapper from "./ui/ProviderWrapper";

export const metadata: Metadata = {
  title: "CREATING PERSONAL KEGEL PLAN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center">
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
